name: TestNG CI

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run TestNG Tests
        run: mvn test -Dsurefire.suiteXmlFiles=src/test/resources/ex4.xml

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: testng-reports
          path: target/surefire-reports/